/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_MouseMotion */

#ifndef _Included_controller_MouseMotion
#define _Included_controller_MouseMotion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_MouseMotion
 * Method:    up
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_up
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    down
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_down
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    left
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_left
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    right
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_right
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    moveTo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_moveTo
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     controller_MouseMotion
 * Method:    moveBy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_moveBy
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     controller_MouseMotion
 * Method:    leftDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_leftDown
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    leftUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_leftUp
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    rightDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_rightDown
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    rightUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_rightUp
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    middleDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_middleDown
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    middleUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_middleUp
  (JNIEnv *, jclass);

/*
 * Class:     controller_MouseMotion
 * Method:    wheelRotate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_controller_MouseMotion_wheelRotate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
